---
# Database
spring:
  datasource:
    url: jdbc:postgresql://${LEARNING_OUTCOME_DB}:5432/${LEARNING_OUTCOME_DB_NAME}
    password: ${LEARNING_OUTCOME_DB_PW}
    username: ${LEARNING_OUTCOME_DB_USER}
  # kafka servers
  kafka:
    bootstrap-servers: kafka:9092
# Keycloak
keycloak:
  auth-server-url: http://keycloak:8090/auth/

# CORS
security:
  cors:
    allowed-origins: '*'
    allowed-headers: '*'
    allowed-methods: '*'
# Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-1:8761/eureka/
