---
# TODO decide if h2 should run in postgresql mode for better compatibility with prod env
# spring.datasource.url=jdbc:h2:~/test;MODE=PostgreSQL
# H2 Dialect
server:
  port: 8081
spring:
  jpa:
    properties:
      hibernate:
        dialect: io.archilab.coalbase.learningoutcomeservice.core.local.H2DialectCustom
  # Kafka
  kafka:
    bootstrap-servers: localhost:9090
# Keycloak
keycloak:
  auth-server-url: http://localhost:8090/auth/
# CORS
security:
  cors:
    allowed-origins: '*'
    allowed-headers: '*'
    allowed-methods: '*'
# Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
    enabled: false
