---
spring:
  datasource:
    url: jdbc:postgresql://${LEARNING_OUTCOME_DB}:5432/${LEARNING_OUTCOME_DB_NAME}
    password: ${LEARNING_OUTCOME_DB_PW}
    username: ${LEARNING_OUTCOME_DB_USER}
  # kafka servers
  kafka:
    bootstrap-servers: kafka-1:9092,kafka-2:9092,kafka-3:9092
# Keycloak
keycloak:
  auth-server-url: https://login.coalbase.io/auth/
# CORS
security:
  cors:
    allowed-origins: 'coalbase.io'
    allowed-headers: '*'
    allowed-methods: '*'
# Eureka
eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-1:8761/eureka/,http://eureka-2:8761/eureka/

